/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface EmailHistory {
  'id' : bigint,
  'status' : EmailStatus,
  'subject' : string,
  'templateId' : bigint,
  'recruiterEmail' : string,
  'recruiterName' : string,
  'sentAt' : bigint,
  'company' : string,
  'jobTitle' : string,
  'repliedAt' : [] | [bigint],
  'openedAt' : [] | [bigint],
}
export type EmailStatus = { 'pending' : null } |
  { 'sent' : null } |
  { 'failed' : null };
export interface EmailTemplate {
  'id' : bigint,
  'subject' : string,
  'body' : string,
  'name' : string,
  'createdAt' : bigint,
  'isActive' : boolean,
  'variables' : Array<string>,
  'updatedAt' : bigint,
}
export interface Resume {
  'id' : bigint,
  'name' : string,
  'isDefault' : boolean,
  'uploadedAt' : bigint,
}
export interface SmtpConfig {
  'host' : string,
  'password' : string,
  'port' : bigint,
  'email' : string,
  'isConnected' : boolean,
  'fromName' : string,
  'replyTo' : string,
  'encryptionType' : string,
}
export interface _SERVICE {
  'createEmailHistory' : ActorMethod<[EmailHistory], EmailHistory>,
  'createEmailTemplate' : ActorMethod<
    [string, string, string, Array<string>],
    EmailTemplate
  >,
  'createResume' : ActorMethod<[string, boolean], Resume>,
  'deleteEmailHistory' : ActorMethod<[bigint], boolean>,
  'deleteEmailTemplate' : ActorMethod<[bigint], boolean>,
  'deleteResume' : ActorMethod<[bigint], boolean>,
  'getAllEmailHistory' : ActorMethod<[], Array<EmailHistory>>,
  'getAllEmailTemplates' : ActorMethod<[], Array<EmailTemplate>>,
  'getAllResumes' : ActorMethod<[], Array<Resume>>,
  'getEmailTemplate' : ActorMethod<[bigint], [] | [EmailTemplate]>,
  'getSmtpConfig' : ActorMethod<[], [] | [SmtpConfig]>,
  'markDefaultResume' : ActorMethod<[bigint], [] | [Resume]>,
  'markEmailHistoryPending' : ActorMethod<[bigint], [] | [EmailHistory]>,
  'seedData' : ActorMethod<[], undefined>,
  'setSmtpConfig' : ActorMethod<[SmtpConfig], undefined>,
  'updateEmailTemplate' : ActorMethod<
    [bigint, string, string, Array<string>],
    [] | [EmailTemplate]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];