/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EmailStatus = IDL.Variant({
  'pending' : IDL.Null,
  'sent' : IDL.Null,
  'failed' : IDL.Null,
});
export const EmailHistory = IDL.Record({
  'id' : IDL.Nat,
  'status' : EmailStatus,
  'subject' : IDL.Text,
  'templateId' : IDL.Nat,
  'recruiterEmail' : IDL.Text,
  'recruiterName' : IDL.Text,
  'sentAt' : IDL.Int,
  'company' : IDL.Text,
  'jobTitle' : IDL.Text,
  'repliedAt' : IDL.Opt(IDL.Int),
  'openedAt' : IDL.Opt(IDL.Int),
});
export const EmailTemplate = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'body' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'variables' : IDL.Vec(IDL.Text),
  'updatedAt' : IDL.Int,
});
export const Resume = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isDefault' : IDL.Bool,
  'uploadedAt' : IDL.Int,
});
export const SmtpConfig = IDL.Record({
  'host' : IDL.Text,
  'password' : IDL.Text,
  'port' : IDL.Nat,
  'email' : IDL.Text,
  'isConnected' : IDL.Bool,
  'fromName' : IDL.Text,
  'replyTo' : IDL.Text,
  'encryptionType' : IDL.Text,
});

export const idlService = IDL.Service({
  'createEmailHistory' : IDL.Func([EmailHistory], [EmailHistory], []),
  'createEmailTemplate' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [EmailTemplate],
      [],
    ),
  'createResume' : IDL.Func([IDL.Text, IDL.Bool], [Resume], []),
  'deleteEmailHistory' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteEmailTemplate' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteResume' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllEmailHistory' : IDL.Func([], [IDL.Vec(EmailHistory)], ['query']),
  'getAllEmailTemplates' : IDL.Func([], [IDL.Vec(EmailTemplate)], ['query']),
  'getAllResumes' : IDL.Func([], [IDL.Vec(Resume)], ['query']),
  'getEmailTemplate' : IDL.Func([IDL.Nat], [IDL.Opt(EmailTemplate)], ['query']),
  'getSmtpConfig' : IDL.Func([], [IDL.Opt(SmtpConfig)], ['query']),
  'markDefaultResume' : IDL.Func([IDL.Nat], [IDL.Opt(Resume)], []),
  'markEmailHistoryPending' : IDL.Func([IDL.Nat], [IDL.Opt(EmailHistory)], []),
  'seedData' : IDL.Func([], [], []),
  'setSmtpConfig' : IDL.Func([SmtpConfig], [], []),
  'updateEmailTemplate' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Opt(EmailTemplate)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EmailStatus = IDL.Variant({
    'pending' : IDL.Null,
    'sent' : IDL.Null,
    'failed' : IDL.Null,
  });
  const EmailHistory = IDL.Record({
    'id' : IDL.Nat,
    'status' : EmailStatus,
    'subject' : IDL.Text,
    'templateId' : IDL.Nat,
    'recruiterEmail' : IDL.Text,
    'recruiterName' : IDL.Text,
    'sentAt' : IDL.Int,
    'company' : IDL.Text,
    'jobTitle' : IDL.Text,
    'repliedAt' : IDL.Opt(IDL.Int),
    'openedAt' : IDL.Opt(IDL.Int),
  });
  const EmailTemplate = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'body' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'variables' : IDL.Vec(IDL.Text),
    'updatedAt' : IDL.Int,
  });
  const Resume = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isDefault' : IDL.Bool,
    'uploadedAt' : IDL.Int,
  });
  const SmtpConfig = IDL.Record({
    'host' : IDL.Text,
    'password' : IDL.Text,
    'port' : IDL.Nat,
    'email' : IDL.Text,
    'isConnected' : IDL.Bool,
    'fromName' : IDL.Text,
    'replyTo' : IDL.Text,
    'encryptionType' : IDL.Text,
  });
  
  return IDL.Service({
    'createEmailHistory' : IDL.Func([EmailHistory], [EmailHistory], []),
    'createEmailTemplate' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [EmailTemplate],
        [],
      ),
    'createResume' : IDL.Func([IDL.Text, IDL.Bool], [Resume], []),
    'deleteEmailHistory' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteEmailTemplate' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteResume' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllEmailHistory' : IDL.Func([], [IDL.Vec(EmailHistory)], ['query']),
    'getAllEmailTemplates' : IDL.Func([], [IDL.Vec(EmailTemplate)], ['query']),
    'getAllResumes' : IDL.Func([], [IDL.Vec(Resume)], ['query']),
    'getEmailTemplate' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(EmailTemplate)],
        ['query'],
      ),
    'getSmtpConfig' : IDL.Func([], [IDL.Opt(SmtpConfig)], ['query']),
    'markDefaultResume' : IDL.Func([IDL.Nat], [IDL.Opt(Resume)], []),
    'markEmailHistoryPending' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(EmailHistory)],
        [],
      ),
    'seedData' : IDL.Func([], [], []),
    'setSmtpConfig' : IDL.Func([SmtpConfig], [], []),
    'updateEmailTemplate' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Opt(EmailTemplate)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };