/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface EmailTemplate {
    id: bigint;
    subject: string;
    body: string;
    name: string;
    createdAt: bigint;
    isActive: boolean;
    variables: Array<string>;
    updatedAt: bigint;
}
export interface EmailHistory {
    id: bigint;
    status: EmailStatus;
    subject: string;
    templateId: bigint;
    recruiterEmail: string;
    recruiterName: string;
    sentAt: bigint;
    company: string;
    jobTitle: string;
    repliedAt?: bigint;
    openedAt?: bigint;
}
export interface Resume {
    id: bigint;
    name: string;
    isDefault: boolean;
    uploadedAt: bigint;
}
export interface SmtpConfig {
    host: string;
    password: string;
    port: bigint;
    email: string;
    isConnected: boolean;
    fromName: string;
    replyTo: string;
    encryptionType: string;
}
export enum EmailStatus {
    pending = "pending",
    sent = "sent",
    failed = "failed"
}
export interface backendInterface {
    createEmailHistory(record: EmailHistory): Promise<EmailHistory>;
    createEmailTemplate(name: string, subject: string, body: string, variables: Array<string>): Promise<EmailTemplate>;
    createResume(name: string, isDefault: boolean): Promise<Resume>;
    deleteEmailHistory(id: bigint): Promise<boolean>;
    deleteEmailTemplate(id: bigint): Promise<boolean>;
    deleteResume(id: bigint): Promise<boolean>;
    getAllEmailHistory(): Promise<Array<EmailHistory>>;
    getAllEmailTemplates(): Promise<Array<EmailTemplate>>;
    getAllResumes(): Promise<Array<Resume>>;
    getEmailTemplate(id: bigint): Promise<EmailTemplate | null>;
    getSmtpConfig(): Promise<SmtpConfig | null>;
    markDefaultResume(id: bigint): Promise<Resume | null>;
    markEmailHistoryPending(id: bigint): Promise<EmailHistory | null>;
    seedData(): Promise<void>;
    setSmtpConfig(config: SmtpConfig): Promise<void>;
    updateEmailTemplate(id: bigint, subject: string, body: string, variables: Array<string>): Promise<EmailTemplate | null>;
}
import type { EmailHistory as _EmailHistory, EmailStatus as _EmailStatus, EmailTemplate as _EmailTemplate, Resume as _Resume, SmtpConfig as _SmtpConfig } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createEmailHistory(arg0: EmailHistory): Promise<EmailHistory> {
        if (this.processError) {
            try {
                const result = await this.actor.createEmailHistory(to_candid_EmailHistory_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_EmailHistory_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEmailHistory(to_candid_EmailHistory_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_EmailHistory_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createEmailTemplate(arg0: string, arg1: string, arg2: string, arg3: Array<string>): Promise<EmailTemplate> {
        if (this.processError) {
            try {
                const result = await this.actor.createEmailTemplate(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEmailTemplate(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createResume(arg0: string, arg1: boolean): Promise<Resume> {
        if (this.processError) {
            try {
                const result = await this.actor.createResume(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createResume(arg0, arg1);
            return result;
        }
    }
    async deleteEmailHistory(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEmailHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEmailHistory(arg0);
            return result;
        }
    }
    async deleteEmailTemplate(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEmailTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEmailTemplate(arg0);
            return result;
        }
    }
    async deleteResume(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteResume(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteResume(arg0);
            return result;
        }
    }
    async getAllEmailHistory(): Promise<Array<EmailHistory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmailHistory();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmailHistory();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEmailTemplates(): Promise<Array<EmailTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmailTemplates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmailTemplates();
            return result;
        }
    }
    async getAllResumes(): Promise<Array<Resume>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllResumes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllResumes();
            return result;
        }
    }
    async getEmailTemplate(arg0: bigint): Promise<EmailTemplate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmailTemplate(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmailTemplate(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSmtpConfig(): Promise<SmtpConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSmtpConfig();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSmtpConfig();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async markDefaultResume(arg0: bigint): Promise<Resume | null> {
        if (this.processError) {
            try {
                const result = await this.actor.markDefaultResume(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markDefaultResume(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async markEmailHistoryPending(arg0: bigint): Promise<EmailHistory | null> {
        if (this.processError) {
            try {
                const result = await this.actor.markEmailHistoryPending(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markEmailHistoryPending(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async seedData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedData();
            return result;
        }
    }
    async setSmtpConfig(arg0: SmtpConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSmtpConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSmtpConfig(arg0);
            return result;
        }
    }
    async updateEmailTemplate(arg0: bigint, arg1: string, arg2: string, arg3: Array<string>): Promise<EmailTemplate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmailTemplate(arg0, arg1, arg2, arg3);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmailTemplate(arg0, arg1, arg2, arg3);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_EmailHistory_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmailHistory): EmailHistory {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_EmailStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmailStatus): EmailStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EmailTemplate]): EmailTemplate | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SmtpConfig]): SmtpConfig | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Resume]): Resume | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EmailHistory]): EmailHistory | null {
    return value.length === 0 ? null : from_candid_EmailHistory_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _EmailStatus;
    subject: string;
    templateId: bigint;
    recruiterEmail: string;
    recruiterName: string;
    sentAt: bigint;
    company: string;
    jobTitle: string;
    repliedAt: [] | [bigint];
    openedAt: [] | [bigint];
}): {
    id: bigint;
    status: EmailStatus;
    subject: string;
    templateId: bigint;
    recruiterEmail: string;
    recruiterName: string;
    sentAt: bigint;
    company: string;
    jobTitle: string;
    repliedAt?: bigint;
    openedAt?: bigint;
} {
    return {
        id: value.id,
        status: from_candid_EmailStatus_n7(_uploadFile, _downloadFile, value.status),
        subject: value.subject,
        templateId: value.templateId,
        recruiterEmail: value.recruiterEmail,
        recruiterName: value.recruiterName,
        sentAt: value.sentAt,
        company: value.company,
        jobTitle: value.jobTitle,
        repliedAt: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.repliedAt)),
        openedAt: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.openedAt))
    };
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    sent: null;
} | {
    failed: null;
}): EmailStatus {
    return "pending" in value ? EmailStatus.pending : "sent" in value ? EmailStatus.sent : "failed" in value ? EmailStatus.failed : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EmailHistory>): Array<EmailHistory> {
    return value.map((x)=>from_candid_EmailHistory_n5(_uploadFile, _downloadFile, x));
}
function to_candid_EmailHistory_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmailHistory): _EmailHistory {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_EmailStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmailStatus): _EmailStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: EmailStatus;
    subject: string;
    templateId: bigint;
    recruiterEmail: string;
    recruiterName: string;
    sentAt: bigint;
    company: string;
    jobTitle: string;
    repliedAt?: bigint;
    openedAt?: bigint;
}): {
    id: bigint;
    status: _EmailStatus;
    subject: string;
    templateId: bigint;
    recruiterEmail: string;
    recruiterName: string;
    sentAt: bigint;
    company: string;
    jobTitle: string;
    repliedAt: [] | [bigint];
    openedAt: [] | [bigint];
} {
    return {
        id: value.id,
        status: to_candid_EmailStatus_n3(_uploadFile, _downloadFile, value.status),
        subject: value.subject,
        templateId: value.templateId,
        recruiterEmail: value.recruiterEmail,
        recruiterName: value.recruiterName,
        sentAt: value.sentAt,
        company: value.company,
        jobTitle: value.jobTitle,
        repliedAt: value.repliedAt ? candid_some(value.repliedAt) : candid_none(),
        openedAt: value.openedAt ? candid_some(value.openedAt) : candid_none()
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmailStatus): {
    pending: null;
} | {
    sent: null;
} | {
    failed: null;
} {
    return value == EmailStatus.pending ? {
        pending: null
    } : value == EmailStatus.sent ? {
        sent: null
    } : value == EmailStatus.failed ? {
        failed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
